version: '3.4'

services:
  520pythonapp:
    image: 520pythonapp
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run --no-debugger --no-reload --host 0.0.0.0 --port 5005"]
    ports:
      - 5005:5005
      - 5678:5678
    environment:
      - FLASK_APP=venv/lib/python3.10/site-packages/lazy_object_proxy/simple.py
